
name: Send Deadline Reminders

on:
  schedule:
    - cron: '0 14 * * *' 
  
  workflow_dispatch:

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Decode Firebase Service Account Key
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_BASE64 }}" | base64 --decode > ${{ github.workspace }}/google-credentials.json

      - name: Install dependencies for script
        run: npm install firebase firebase-admin resend

      - name: Run reminder script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/google-credentials.json
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
          VITE_AUTH_DOMAIN: ${{ secrets.VITE_AUTH_DOMAIN }}
          VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID }}
          VITE_STORAGE_BUCKET: ${{ secrets.VITE_STORAGE_BUCKET }}
          VITE_MESSAGING_SENDER_ID: ${{ secrets.VITE_MESSAGING_SENDER_ID }}
          VITE_APP_ID: ${{ secrets.VITE_APP_ID }}
        run: node send-reminders.js